apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb-vpp
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: vpp-lab
      defaultBucket: vpp
      tlsSkipVerify: true
    secureJsonData:
      token: vpp-lab-token
